version: '2'

services:
  nutracker-prod:
    container_name: nutracker-prod
    build:
      context: .
      dockerfile: Dockerfile
      args:
        BUILD_ENV: alpha
    ports:
      - '8008:8008'

